#!/bin/bash

SQLITE=`which sqlite3`;

rm dbdata;

$SQLITE dbdata "create table events (ev_id integer primary key, id text, name text, typ text, status integer, message text, datum datetime);"
$SQLITE dbdata "create table triggers (tr_id integer primary key, tr_name text, datum datetime);"


