#!/usr/bin/perl
use strict;
use warnings;
use DBI;

# project:      jarvis - Just Another Really Versatile Information System
# part:         jarvis_report - generate reports from jarvis data
# author:       see AUTHORS
# license:      BEER-WARE
# version:      0.1a


# first of all, parse the args

if (scalar @ARGV < 2) {
    die "You have to specify at least a start and an end date!\n";
}

# the first param is start date and time, the second is end
my ($start, $end) = (shift, shift);

# we need pdflatex
my $PDFLATEX = `which pdflatex`;

# connect to database
my $dbargs = {AutoCommit => 0, PrintError => 1};
my $dbh = DBI->connect("dbi:SQLite:dbname=/opt/jarvis/jarvis.db", "", "", $dbargs);

# default header and footer for latex doc
my $latexheader = <<'EOHEAD';
\documentclass[12pt]{scrartcl}
\usepackage{graphicx}
EOHEAD

my $latexfooter = <<'EOFOOT';
\end{document}
EOFOOT

my $all_services = $dbh->prepare("SELECT distinct(name), typ from events;");
$all_services->execute() or die "can't blabla";


# display all activated agents
while(my ($name, $typ) = $all_services->fetchrow_array()) {
    print "$name : $typ\n";
}


$dbh->disconnect();






