#!/usr/bin/perl
use strict;
use warnings;
use Filesys::Df;
use lib "./agents/";
use JarvisFunctions;

# what module is this?
my $agent_name = "DiskUsageCheck";

# every agent gets an id and the name from jarvis when started
my ($id, $name) = @ARGV;

# params just for this agent, not directly given from jarvis. we will
# get them from the config later.

my ($mountpoint, $interval, $maxperc);

# because every agent is different, we need to get the data from the config
my $config = "/home/ap0calypse/projects/jarvis/example-config";

open my $CONFFD, "< $config" or die "$0: $!";
while (<$CONFFD>) {
    next if m/^\s*#.*/;
    # got the config entry
    if (m/.*agent=\[$agent_name,"$name", *(\d+) *, *(.+) *, *(\d+) *\]/) {
        ($interval, $mountpoint, $maxperc) = ($1, $2, $3);
    }
    else {
        next;
    }
}
close $CONFFD;

while(1) {
    my $ref = df($mountpoint);
    if ($ref->{'per'} > $maxperc) {
        tell_jarvis($id, $name, $agent_name, 0, $ref->{'per'});
    }
    else {
        tell_jarvis($id, $name, $agent_name, 1, $ref->{'per'});
    }
    sleep($interval);
}

