#!/usr/bin/perl
use strict;
use warnings;
use lib "./agents/";
use JarvisFunctions;

# what module is this?
my $agent_name = "FileExistsCheck";

# every agent gets an id and the name from jarvis when started
my ($id, $name) = @ARGV;

# params just for this agent, not directly given from jarvis. we will
# get them from the config later.

my ($path, $interval);

# because every agent is different, we need to get the data from the config
my $config = get_config();

open my $CONFFD, "< $config" or die "$0: $!";
while (<$CONFFD>) {
    next if m/^\s*#.*/;
    # got the config entry
    if (m/.*agent=\[$agent_name,"$name", *(\d+) *, *'(.+)' *\]/) {
        ($interval, $path) = ($1, $2);
    }
    else {
        next;
    }
}
close $CONFFD;

while(1) {
    if (-e "$path") {
        tell_jarvis($id, $name, $agent_name, 1, "OK");
    }
    else {
        tell_jarvis($id, $name, $agent_name, 0, "NOT OK");
    }
    sleep($interval);
}

