#!/usr/bin/perl
use strict;
use warnings;
use lib "./agents/";
use JarvisFunctions;

# what module is this?
my $agent_name = "FileSizeCheck";

# every agent gets an id and the name from jarvis when started
my ($id, $name) = @ARGV;

# params just for this agent, not directly given from jarvis. we will
# get them from the config later.

my ($path, $interval, $maxsize);

# because every agent is different, we need to get the data from the config
my $config = "/home/ap0calypse/projects/jarvis/example-config";

open my $CONFFD, "< $config" or die "$0: $!";
while (<$CONFFD>) {
    next if m/^\s*#.*/;
    # got the config entry
    if (m/.*agent=\[$agent_name,"$name", *(\d+) *, *'(.+)' *, *(\d+) *\]/) {
        ($interval, $path, $maxsize) = ($1, $2, $3);
    }
    else {
        next;
    }
}
close $CONFFD;

while(1) {
    my $size= (stat $path)[7];
    if ($size > $maxsize) {
        tell_jarvis($id, $name, $agent_name, 0, $size);
    }
    else {
        tell_jarvis($id, $name, $agent_name, 1, $size);
    }
    sleep($interval);
}

