#!/usr/bin/perl
use strict;
use warnings;
use Proc::ProcessTable;
use lib "./agents/";
use JarvisFunctions;


# what module is this?
my $agent_name = "ProcessCheck";

# every agent gets an id and the name from jarvis when started
my ($id, $name) = @ARGV;

# params just for this agent, not directly given from jarvis. we will
# get them from the config later.

my ($procname, $interval);

# because every agent is different, we need to get the data from the config
my $config = get_config(); 

open my $CONFFD, "< $config" or die "$0: $!";
while (<$CONFFD>) {
    next if m/^\s*#.*/;
    # got the config entry
    if (m/.*agent=\[$agent_name,"$name", *(\d+) *, *'(.+)' *\]/) {
        ($interval, $procname) = ($1, $2);
    }
    else {
        next;
    }
}
close $CONFFD;

while(1) {
    my $t = Proc::ProcessTable->new();
    my $is_running = 0;
    for my $p (@{$t->table()}) {
        if ($p->cmndline() =~ m/$procname/) {
            $is_running = 1;
        }
    }
    tell_jarvis($id, $name, $agent_name, $is_running, $procname);
    sleep($interval);
}

