#!/usr/bin/perl
use strict;
use warnings;
use IO::Socket;
use lib "./agents/";
use JarvisFunctions;

# what module is this?
my $agent_name = "TCPConnect";

# every agent gets an id and the name from osiris when started
my ($id, $name) = @ARGV;

# params just for this agent, not directly given from osiris. we will
# get them from the config later.

my ($port, $host, $interval);

# because every agent is different, we need to get the data from the config
my $config = "/home/ap0calypse/projects/jarvis/example-config";

open my $CONFFD, "< $config" or die "$0: $!";
while (<$CONFFD>) {
    # got the config entry
    if (m/\[$agent_name,"$name",(.+),(.+),(.+)\]/) {
        ($port, $host, $interval) = ($3, $2, $1);
    }
    else {
        next;
    }
}
close $CONFFD;


# now we really start
while(1) {
    my $rem = IO::Socket::INET->new(
        Proto    => "tcp",
        PeerAddr => "$host",
        PeerPort => $port,
    );
    if (defined $rem) {
       tell_jarvis($id, $name, $agent_name, 1, "OK"); 
       close($rem);
    }
    else {
        tell_jarvis($id, $name, $agent_name, 0, "NOT OK");
    }
    sleep($interval);
}
